export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  SHELTER_NOT_FOUND: "SHELTER_NOT_FOUND",
  SHELTER_NOT_OPEN: "SHELTER_NOT_OPEN",
  CAPACITY_EXCEEDED: "CAPACITY_EXCEEDED",
  INSUFFICIENT_POPULATION: "INSUFFICIENT_POPULATION",
  SHELTER_NOT_EMPTY: "SHELTER_NOT_EMPTY",
  INVALID_AMOUNT: "INVALID_AMOUNT",
  SAME_SHELTER: "SAME_SHELTER"
} as const;
